#!/bin/bash -x

read -p "Enter a number: " num

function palindrome()
{
	
	n1=$num
	rev=0
	while (( num > 0 ))
	do
		rem=$(( num % 10 ))
		rev=$(( rev * 10 + rem ))
		(( num = num / 10 ))
	done
	if [ $rev -eq $n1 ]
	then
		echo "$n1 is palindrome"
	else
		echo "$n1 is not palindrome"
	fi
}
palindrome $num
